# Numpy
```
pip install numpy
```

- Mathematical Calculations
- Numpy Array Creation
- Shape
- indexing
- data types: b,i,u,f,c,m,M,O,S,u,V (https://numpy.org/doc/1.25/reference/arrays.dtypes.html#arrays-dtypes)
- more creation methods: arange, linspace, ones, zeros, eye, diag
- random numbers: Numpy Random Module
    - rand: Random values in given shape
    - randn: Return samples from the Standard normal distribution
    - randint: Return random integer from low(inclusive) to high(exclusive)
    - random: Return random floats in [0.0,1.0)
    - choice: Generates a random sample from given 1D array
    - Shuffle: Shuffle the contents of the sequence. Discuss np.random.seed()
- reshape: -1 for unknown
- slicing and assignment
- copy and view: share_memory
- operators(Element wise operations)
- and: &, or: |, not: ~ (Bitwise works same as logical in case of boolean Values)
- shape mismatch
- fancy indexing also know as filter
- search: where uses fancy indexing
- Basic reductions: sum, min, max, any, all,argmax, argmin
- Some More Numpy Functions - Statistics: mean, median, average, variance, standard deviation
- iteration: nditer, ndenumerate
- Join: concatenate, stack, hstack, vstack. Note: make a tuple of arays you want to join
- split: array_split, hsplit
- sort: np.sort
- Broadcasting
- Input from Text File
- Questions

In [1]:
!pip install numpy

In [2]:
import numpy as np
print(np.__version__)

1.26.4


In [145]:
l = [[1,2],[3,4,5],[6,7]]
n = np.array(l,dtype='object')
n

array([list([1, 2]), list([3, 4, 5]), list([6, 7])], dtype=object)

In [24]:
l1 = [1,2,3.1,4]
l2 = [[1,2],[3,4],[5,6]]
l3 = [[[10,20],[30,40]],[[1,2],[3,4]],[[1,2],[3,4]]]

In [25]:
print(l2[1][1])

4


In [26]:
print(l3[2][1][1])

4


In [88]:
n1 = np.array(l1,dtype='int64')
n2 = np.array(l2,dtype='f2')#1 2 4 8
n3 = np.array(l3)

In [89]:
n1

array([1, 2, 3, 4], dtype=int64)

In [90]:
n2

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [91]:
n3

array([[[10, 20],
        [30, 40]],

       [[ 1,  2],
        [ 3,  4]],

       [[ 1,  2],
        [ 3,  4]]])

In [92]:
n1.shape

(4,)

In [93]:
n2.shape

(3, 2)

In [94]:
n3.shape

(3, 2, 2)

In [95]:
n1.dtype

dtype('int64')

In [96]:
n2.dtype

dtype('float16')

In [87]:
n2

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [55]:
n2[2,1]

6

In [33]:
print(l1[2],n1[2])

3 3.0


In [58]:
print(type(n2),type(n2[2]),type(n2[2][1]))

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.int32'>


In [59]:
print(l3[0][1][0],n3[0,1,0])

30 30


In [60]:
l2[1]

[3, 4]

In [61]:
n2[1]

array([3, 4])

In [65]:
n2[2,4]

IndexError: index 4 is out of bounds for axis 1 with size 2

In [68]:
n3.ndim

3

more creation methods: arange, linspace, ones, zeros, eye, diag

In [97]:
narr = np.arange(1,11,2)

In [98]:
narr

array([1, 3, 5, 7, 9])

In [103]:
np.linspace(1,100,5,dtype='i')

array([  1,  25,  50,  75, 100], dtype=int32)

In [106]:
np.ones(shape = (2,3,2),dtype='i')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [107]:
np.zeros(shape=(5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [111]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [112]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [113]:
narr = np.arange(1,101)

In [114]:
narr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [135]:
narr = narr.reshape((4,-1,5))

In [136]:
narr.shape

(4, 5, 5)

In [138]:
narr.reshape((-1,))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

random numbers: Numpy Random Module
- rand: Random values in given shape
- randn: Return samples from the Standard normal distribution
- randint: Return random integer from low(inclusive) to high(exclusive)
- random: Return random floats in [0.0,1.0)
- choice: Generates a random sample from given 1D array
- Shuffle: Shuffle the contents of the sequence. Discuss np.random.seed()

In [166]:
np.random.seed(100)
np.random.rand(3,2,3)

array([[[0.54340494, 0.27836939, 0.42451759],
        [0.84477613, 0.00471886, 0.12156912]],

       [[0.67074908, 0.82585276, 0.13670659],
        [0.57509333, 0.89132195, 0.20920212]],

       [[0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101]]])

In [148]:
np.random.random(size = (3,2))

array([[0.67697212, 0.61215993],
       [0.68973664, 0.97428927],
       [0.00351141, 0.92002787]])

In [90]:
np.random.randn(3,2,2)

array([[[-0.0120514 ,  0.89957771],
        [ 0.09633878, -1.66630393]],

       [[-0.83800518,  0.99848272],
        [ 1.0702597 ,  0.39286891]],

       [[ 0.17500246,  0.58892847],
        [-1.12652496, -0.62376908]]])

In [92]:
np.random.randint(1,101,size=(5,2))

array([[74, 44],
       [98, 49],
       [19, 34],
       [65, 11],
       [17, 97]])

In [151]:
np.random.choice(np.array([1,2,3,4,5,6,7,8,9]),size=(5,2),replace = True,p = [0.1,0,0,0,0.2,0.3,0.1,0,0.3])

array([[6, 9],
       [7, 6],
       [1, 6],
       [5, 7],
       [1, 5]])

In [98]:
narr = np.arange(1,11)

In [99]:
narr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
np.random.shuffle(narr)

In [101]:
narr

array([ 5,  4,  8, 10,  7,  9,  6,  3,  2,  1])

In [117]:
narr.sort()
narr

narr = narr.reshape((2,5))

In [119]:
narr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [167]:
narr = np.arange(1,101)
narr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [168]:
narr = narr.reshape((10,10))

In [173]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,   1,   1,   1,   1,  48,  49,  50],
       [ 51,  52,  53,   1,   1,   1,   1,  58,  59,  60],
       [ 61,  62,  63,   1,   1,   1,   1,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [172]:
narr[4:7,3:7] = 1

In [138]:
narr[:,2:7]

array([[ 3,  4,  5,  6,  7],
       [13, 14, 15, 16, 17],
       [23, 24, 25, 26, 27],
       [33, 34, 35, 36, 37],
       [43, 44, 45, 46, 47],
       [53, 54, 55, 56, 57],
       [63, 64, 65, 66, 67],
       [73, 74, 75, 76, 77],
       [83, 84, 85, 86, 87],
       [93, 94, 95, 96, 97]])

In [168]:
narr = np.arange(1,101).reshape((10,10))

In [169]:
narr[3:7,4:8] = np.eye(4)

In [175]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,   1,   0,   0,   0,  39,  40],
       [ 41,  42,  43,  44,   0,   1,   0,   0,  49,  50],
       [ 51,  52,  53,  54,   0,   0,   1,   0,  59,  60],
       [ 61,  62,  63,  64,   0,   0,   0,   1,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [147]:
# narr[8] = np.arange(1001,1011)

In [177]:
barr = narr[8:,:]

In [174]:
barr

array([[ 81,  82,   1,   1,   1,   1,   1,  88,  89,  90],
       [ 91,  92,   1,   1,   1,   1,   1,  98,  99, 100]])

In [178]:
np.shares_memory(narr,barr)

True

In [173]:
barr[:,2:7] = 1

In [179]:
l1 = [1,2,3,4,5]
l1+2

TypeError: can only concatenate list (not "int") to list

In [180]:
n1 = np.array([[1,2,3],[4,5,6]])
n2 = np.array([10,20,30,40,50])

In [182]:
n2+3

array([13, 23, 33, 43, 53])

In [183]:
n1-3

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [184]:
n1*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [185]:
n1/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [186]:
n1//3

array([[0, 0, 1],
       [1, 1, 2]], dtype=int32)

In [187]:
n1%3

array([[1, 2, 0],
       [1, 2, 0]], dtype=int32)

In [188]:
n1**3

array([[  1,   8,  27],
       [ 64, 125, 216]], dtype=int32)

In [190]:
n2 > 3

array([ True,  True,  True,  True,  True])

In [192]:
n1 = np.array([[1,2,3],[4,5,6]])
n2 = np.array([[10,20,30],[40,50,60]])

In [193]:
n1+n2

array([[11, 22, 33],
       [44, 55, 66]])

In [23]:
n1-n2

array([[ -9, -18, -27],
       [-36, -45, -54]])

In [24]:
n1*n2

array([[ 10,  40,  90],
       [160, 250, 360]])

In [195]:
n1*10 == n2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [26]:
n1*10+n2

array([[ 20,  40,  60],
       [ 80, 100, 120]])

In [196]:
n1 = np.arange(1,21)

In [197]:
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [198]:
np.random.shuffle(n1)

In [199]:
n1

array([18,  2,  6,  1, 11,  8,  5, 13,  9,  4,  7, 20,  3, 19, 14, 15, 16,
       10, 17, 12])

In [204]:
n1[[2,7,5,10,11,7]]

array([ 6, 13,  8,  7, 20, 13])

In [205]:
narr = np.arange(1,101).reshape((10,10))

In [211]:
narr[[1,2,6,7]] # Rows
narr[:,[1,2,6,7]] #Columns

narr[[2,3,5,6,7],[1,3,5,3,2]]

array([22, 34, 56, 64, 73])

In [214]:
narr[:,[False,True,True,False,False,False,True,True,False,False]]

array([[ 2,  3,  7,  8],
       [12, 13, 17, 18],
       [22, 23, 27, 28],
       [32, 33, 37, 38],
       [42, 43, 47, 48],
       [52, 53, 57, 58],
       [62, 63, 67, 68],
       [72, 73, 77, 78],
       [82, 83, 87, 88],
       [92, 93, 97, 98]])

In [219]:
narr[:,narr[0]%4 == 0]

array([[ 4,  8],
       [14, 18],
       [24, 28],
       [34, 38],
       [44, 48],
       [54, 58],
       [64, 68],
       [74, 78],
       [84, 88],
       [94, 98]])

In [222]:
n1[n1 > 10]

array([18, 11, 13, 20, 19, 14, 15, 16, 17, 12])

In [230]:
narr[narr%6==0]

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

In [61]:
n2 = np.array([[[1,2],[3,4],[5,6]],[[10,20],[30,40],[50,60]]])

In [225]:
n1

array([18,  2,  6,  1, 11,  8,  5, 13,  9,  4,  7, 20,  3, 19, 14, 15, 16,
       10, 17, 12])

In [235]:
n = np.arange(1,13).reshape((2,3,2))

In [236]:
n

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [239]:
n.sum(axis = 2)

array([[ 3,  7, 11],
       [15, 19, 23]])

In [65]:
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
n1.sum(axis = 0)

array([12, 15, 18])

In [67]:
n1.sum(axis = 1)

array([ 6, 15, 24])

In [69]:
n1.max(axis = 0)

array([7, 8, 9])

In [70]:
n1.min(axis = 1)

array([1, 4, 7])

In [240]:
n1

array([18,  2,  6,  1, 11,  8,  5, 13,  9,  4,  7, 20,  3, 19, 14, 15, 16,
       10, 17, 12])

In [241]:
np.argmax(n1)

11

In [242]:
nb = np.array([True,True,True])

In [244]:
np.all(n1 > 0)

True

In [247]:
n

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [249]:
for t in np.nditer(n):
    print(t)

1
2
3
4
5
6
7
8
9
10
11
12


In [251]:
for t in np.ndenumerate(n):
    print(t)

((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 1, 0), 3)
((0, 1, 1), 4)
((0, 2, 0), 5)
((0, 2, 1), 6)
((1, 0, 0), 7)
((1, 0, 1), 8)
((1, 1, 0), 9)
((1, 1, 1), 10)
((1, 2, 0), 11)
((1, 2, 1), 12)


In [252]:
n1 = np.array([1,2,3])
n2 = np.array([10,20,30])

In [253]:
np.vstack((n1,n2))

array([[ 1,  2,  3],
       [10, 20, 30]])

In [87]:
np.hstack((n1,n2))

array([ 1,  2,  3, 10, 20, 30])

In [255]:
np.concatenate((n1,n2),axis = 0)

array([ 1,  2,  3, 10, 20, 30])

In [257]:
np.stack((n1,n2),axis=0)

array([[ 1,  2,  3],
       [10, 20, 30]])

In [258]:
n1

array([1, 2, 3])

In [259]:
l = np.hsplit(n1,3)

In [260]:
l

[array([1]), array([2]), array([3])]

In [261]:
l[0][0] = 10

In [262]:
l

[array([10]), array([2]), array([3])]

In [103]:
n1

array([10,  2,  3])

In [263]:
n1 = np.arange(1,13).reshape(3,4)

In [264]:
n1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [265]:
np.array([10,20,30,40]) + n1

array([[11, 22, 33, 44],
       [15, 26, 37, 48],
       [19, 30, 41, 52]])

In [266]:
np.array([[10],[20],[30]])

array([[10],
       [20],
       [30]])

In [267]:
np.array([[10],[20],[30]]) + n1

array([[11, 12, 13, 14],
       [25, 26, 27, 28],
       [39, 40, 41, 42]])

In [268]:
np.array([10,20,30])+np.array([[10],[20],[30],[40]])

array([[20, 30, 40],
       [30, 40, 50],
       [40, 50, 60],
       [50, 60, 70]])

In [269]:
pop = np.loadtxt('populations.txt')

In [270]:
pop

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [275]:
pop[pop[:,1:].argmax(axis=0),0]

array([1903., 1904., 1900.])

In [271]:
pop.max(axis = 0)

array([ 1920., 77400., 59400., 48300.])

In [277]:
pop[:,1:].max(axis=1)

array([48300., 48200., 70200., 77400., 59400., 41700., 38600., 42300.,
       44500., 42100., 46000., 46800., 57000., 76600., 52300., 51100.,
       36700., 41800., 43300., 41300., 47300.])

In [279]:
names = np.array(['hare','lynx','carrot'])
names[pop[:,1:].argmax(axis=1)]

array(['carrot', 'carrot', 'hare', 'hare', 'lynx', 'lynx', 'carrot',
       'carrot', 'carrot', 'carrot', 'carrot', 'carrot', 'hare', 'hare',
       'hare', 'lynx', 'carrot', 'carrot', 'carrot', 'carrot', 'carrot'],
      dtype='<U6')

In [128]:
n1 = np.arange(1,13).reshape(3,4)

In [129]:
n1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [130]:
n2 = np.array([[1,2,3],[10,20,30]])

In [131]:
n2

array([[ 1,  2,  3],
       [10, 20, 30]])

In [132]:
n2.dot(n1)

array([[ 38,  44,  50,  56],
       [380, 440, 500, 560]])

In [133]:
n2@n1

array([[ 38,  44,  50,  56],
       [380, 440, 500, 560]])

In [3]:
np.matmul([[1,2,3]],[[4],[5],[6]])

array([[32]])

In [4]:
w = np.random.random(5)
x = np.ones((5,10))

In [5]:
w@x

array([2.03349284, 2.03349284, 2.03349284, 2.03349284, 2.03349284,
       2.03349284, 2.03349284, 2.03349284, 2.03349284, 2.03349284])